#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes=""
org.gradle.configuration-cache=false
org.gradle.caching=true

#Network Properties
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.http.keepAlive=false
systemProp.java.net.preferIPv4Stack=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
android.defaults.buildfeatures.resvalues=false
android.builtInKotlin=false
android.newDsl=false

# Performance & Sync
android.dependency.excludeLibraryComponentsFromConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
