package truck.project.designsystem.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage {
    ES, EN
}

data class DsStrings(
    val welcome: String,
    val login: String,
    val email: String,
    val password: String,
    val admin: String,
    val driver: String,
    val fleet: String,
    val routes: String,
    val stats: String,
    val profile: String,
    val logout: String,
    val register: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val loading: String,
    val error: String,
    val controlPanel: String,
    val systemActive: String,
    val activeTrucks: String,
    val drivers: String,
    val todayExpenses: String,
    val live: String,
    val tripsInProgress: String,
    val add: String,
    val available: String,
    val inRoute: String,
    val inspection: String,
    val protocol: String,
    val odometer: String,
    val startRoute: String,
    val fuel: String,
    val toll: String,
    val food: String,
    val lodging: String,
    val others: String
)

val EnStrings = DsStrings(
    welcome = "WELCOME",
    login = "LOGIN",
    email = "EMAIL",
    password = "PASSWORD",
    admin = "ADMIN",
    driver = "DRIVER",
    fleet = "FLEET",
    routes = "ROUTES",
    stats = "STATS",
    profile = "PROFILE",
    logout = "LOGOUT",
    register = "REGISTER",
    save = "SAVE",
    cancel = "CANCEL",
    delete = "DELETE",
    edit = "EDIT",
    loading = "LOADING...",
    error = "ERROR",
    controlPanel = "CONTROL PANEL",
    systemActive = "SYSTEM ACTIVE",
    activeTrucks = "Active",
    drivers = "Drivers",
    todayExpenses = "Today expenses (Bs)",
    live = "LIVE",
    tripsInProgress = "trips in progress",
    add = "ADD",
    available = "AVAILABLE",
    inRoute = "IN ROUTE",
    inspection = "INSPECTION",
    protocol = "DEPARTURE PROTOCOL",
    odometer = "INITIAL ODOMETER (KM)",
    startRoute = "START OFFICIAL ROUTE",
    fuel = "Fuel",
    toll = "Toll",
    food = "Food",
    lodging = "Lodging",
    others = "Others"
)

val EsStrings = DsStrings(
    welcome = "BIENVENIDO",
    login = "INICIAR SESIÓN",
    email = "CORREO ELECTRÓNICO",
    password = "CONTRASEÑA",
    admin = "ADMINISTRADOR",
    driver = "CONDUCTOR",
    fleet = "FLOTA",
    routes = "RUTAS",
    stats = "MÉTRICAS",
    profile = "PERFIL",
    logout = "CERRAR SESIÓN",
    register = "REGISTRARSE",
    save = "GUARDAR",
    cancel = "CANCELAR",
    delete = "ELIMINAR",
    edit = "EDITAR",
    loading = "CARGANDO...",
    error = "ERROR",
    controlPanel = "PANEL DE CONTROL",
    systemActive = "SISTEMA ACTIVO",
    activeTrucks = "Activos",
    drivers = "Conductores",
    todayExpenses = "Gastos hoy",
    live = "EN VIVO",
    tripsInProgress = "viajes en curso",
    add = "AGREGAR",
    available = "LIBRE",
    inRoute = "EN RUTA",
    inspection = "INSPECCIÓN",
    protocol = "PROTOCOLO DE SALIDA",
    odometer = "ODÓMETRO INICIAL (KM)",
    startRoute = "INICIAR RUTA OFICIAL",
    fuel = "Combustible",
    toll = "Peaje",
    food = "Alimentación",
    lodging = "Hospedaje",
    others = "Otros"
)

val LocalDsStrings = staticCompositionLocalOf { EsStrings }
